[package]
name = "iced_wgpu"
version = "0.2.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A wgpu renderer for Iced"
license = "MIT AND OFL-1.1"
repository = "https://github.com/hecrj/iced"

[features]
svg = ["resvg"]
canvas = ["lyon"]

[dependencies]
wgpu = "0.5"
wgpu_glyph = "0.8"
zerocopy = "0.3"
glyph_brush = "0.6"
raw-window-handle = "0.3"
glam = "0.8"
font-kit = "0.4"
log = "0.4"
guillotiere = "0.4"

[dependencies.iced_native]
version = "0.2"
path = "../native"

[dependencies.iced_style]
version = "0.1"
path = "../style"

[dependencies.image]
version = "0.22"
optional = true

[dependencies.resvg]
version = "0.8"
features = ["raqote-backend"]
optional = true

[dependencies.lyon]
version = "0.15"
optional = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
