[package]
name = "iced_wgpu"
version = "0.4.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A wgpu renderer for Iced"
license = "MIT AND OFL-1.1"
repository = "https://github.com/hecrj/iced"

[features]
svg = ["resvg", "usvg", "tiny-skia"]
image = ["png", "jpeg", "jpeg_rayon", "gif", "webp", "bmp"]
png = ["image_rs/png"]
jpeg = ["image_rs/jpeg"]
jpeg_rayon = ["image_rs/jpeg_rayon"]
gif = ["image_rs/gif"]
webp = ["image_rs/webp"]
pnm = ["image_rs/pnm"]
ico = ["image_rs/ico"]
bmp = ["image_rs/bmp"]
hdr = ["image_rs/hdr"]
dds = ["image_rs/dds"]
farbfeld = ["image_rs/farbfeld"]
canvas = ["iced_graphics/canvas"]
qr_code = ["iced_graphics/qr_code"]
default_system_font = ["iced_graphics/font-source"]
spirv = ["wgpu/spirv"]

[dependencies]
wgpu = "0.11"
wgpu_glyph = "0.15"
glyph_brush = "0.7"
raw-window-handle = "0.3"
log = "0.4"
guillotiere = "0.6"
futures = "0.3"
kamadak-exif = "0.5"
bitflags = "1.2"

[dependencies.bytemuck]
version = "1.4"
features = ["derive"]

[dependencies.iced_native]
version = "0.4"
path = "../native"

[dependencies.iced_graphics]
version = "0.2"
path = "../graphics"
features = ["font-fallback", "font-icons"]

[dependencies.image_rs]
version = "0.23"
package = "image"
default-features = false
optional = true

[dependencies.resvg]
version = "0.18"
optional = true

[dependencies.usvg]
version = "0.18"
optional = true

[dependencies.tiny-skia]
version = "0.6"
optional = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true
