[package]
name = "download_progress"
version = "0.1.0"
authors = ["Songtronix <contact@songtronix.com>", "Folyd <lyshuhow@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["tokio"] }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls"]
