[package]
name = "download_progress"
version = "0.1.0"
authors = ["Songtronix <contact@songtronix.com>", "Folyd <lyshuhow@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["tokio"]

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["stream", "rustls-tls"]
