[package]
name = "window_ctl"
version = "0.1.0"
authors = ["cossonleo <cossonleo@foxmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { path = "../.." }
