[package]
name = "tooltip"
version = "0.1.0"
authors = ["Yusuf Bera Ertan <y.bera003.06@protonmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["debug"]
