[package]
name = "loading_spinners"
version = "0.1.0"
authors = ["Nick Senger <dev@nsenger.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["advanced", "canvas"]

lyon_algorithms = "1.0"
once_cell.workspace = true