[package]
name = "iced_sctk"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"
description = "An sctk runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_sctk"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = []

[dependencies]
#framework = { path = "../../framework" }
derive_more = "0"
pin-utils = "^0.1"
futures = "^0.3"
futures-util = "^0.3"
#async-std = { version = "1.5", features = ["unstable"] }
smithay-client-toolkit = { version = "^0.9", default-features=false, features=["frames"], path="../../client-toolkit" } #-calloop #120
#smithay-client-toolkit = { version = "^0.9", default-features=false, features=["frames"] } #-calloop #120
smol = ''
raw-window-handle = "0.3"
#window_clipboard = "0.1"
log = "0.4"
iced_native = { version = "0.2", path = "../native" }

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.6"
