[package]
name = "iced_core"
version = "0.4.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
description = "The essential concepts of Iced"
license = "MIT"
repository = "https://github.com/iced-rs/iced"

[dependencies]
bitflags = "1.2"
twox-hash = { version = "1.5", default-features = false }

[dependencies.palette]
version = "0.5"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-timer = { version = "0.2" }
