[package]
name = "system_information"
version = "0.1.0"
authors = ["Richard <richardsoncusto@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["system"] }
bytesize = { version = "1.1.0" }
