[package]
name = "system_information"
version = "0.1.0"
authors = ["Richard <richardsoncusto@gmail.com>"]
edition = "2024"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["system"]

bytesize = "1.1"
