[package]
name = "the_matrix"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.features = ["canvas", "tokio", "debug"]

rand = "0.8"
tracing-subscriber = "0.3"
