[package]
name = "iced_native"
version = "0.2.2"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A renderer-agnostic library for native GUIs"
license = "MIT"
repository = "https://github.com/hecrj/iced"

[features]
debug = []

[dependencies]
twox-hash = "1.5"
unicode-segmentation = "1.6"

[dependencies.iced_core]
version = "0.2"
path = "../core"

[dependencies.iced_futures]
version = "0.1"
path = "../futures"
features = ["thread-pool"]
