[package]
name = "scrollable"
version = "0.1.0"
authors = ["Clark Moody <clark@clarkmoody.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["debug"] }
lazy_static = "1.4"
