[package]
name = "iced_tiny_skia"
version = "0.1.0"
edition = "2021"

[features]
default = ["gpu"]
gpu = ["pixels"]
image = ["iced_graphics/image"]
svg = ["resvg"]
geometry = ["iced_graphics/geometry"]

[dependencies]
raw-window-handle = "0.5"
softbuffer = "0.2"
tiny-skia = "0.8"
cosmic-text = "0.8"
bytemuck = "1"
rustc-hash = "1.1"
kurbo = "0.9"
log = "0.4"

[dependencies.iced_graphics]
version = "0.7"
path = "../graphics"
features = ["tiny-skia"]

[dependencies.twox-hash]
version = "1.6"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.twox-hash]
version = "1.6.1"
features = ["std"]

[dependencies.pixels]
version = "0.12"
optional = true

[dependencies.resvg]
version = "0.29"
optional = true
