[package]
name = "iced_renderer"
version = "0.1.0"
edition = "2021"

[features]
wgpu = ["iced_wgpu"]
image = ["iced_tiny_skia/image", "iced_wgpu?/image"]
svg = ["iced_tiny_skia/svg", "iced_wgpu?/svg"]
geometry = ["iced_graphics/geometry", "iced_tiny_skia/geometry", "iced_wgpu?/geometry"]
tracing = ["iced_wgpu?/tracing"]
web-colors = ["iced_wgpu?/web-colors"]

[dependencies]
raw-window-handle = "0.5"
thiserror = "1"

[dependencies.iced_graphics]
version = "0.8"
path = "../graphics"

[dependencies.iced_tiny_skia]
version = "0.1"
path = "../tiny_skia"

[dependencies.iced_wgpu]
version = "0.10"
path = "../wgpu"
optional = true
