[package]
name = "iced_glutin"
version = "0.2.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A glutin runtime for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_glutin"
keywords = ["gui", "ui", "graphics", "interface", "widgets"]
categories = ["gui"]

[features]
debug = ["iced_winit/debug"]

[dependencies.glutin]
version = "0.27"
git = "https://github.com/iced-rs/glutin"
rev = "492c20605907accf2b5dc2da52284305fd128346"

[dependencies.iced_native]
version = "0.4"
path = "../native"

[dependencies.iced_winit]
version = "0.3"
path = "../winit"

[dependencies.iced_graphics]
version = "0.2"
path = "../graphics"
features = ["opengl"]
