[package]
name = "iced_web"
version = "0.4.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "A web backend for Iced"
license = "MIT"
repository = "https://github.com/hecrj/iced"
documentation = "https://docs.rs/iced_web"
readme = "README.md"
keywords = ["gui", "ui", "web", "interface", "widgets"]
categories = ["web-programming"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
dodrio = "0.2"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
url = "2.0"
num-traits = "0.2"
base64 = "0.13"

[dependencies.iced_core]
version = "0.4"
path = "../core"

[dependencies.iced_futures]
version = "0.3"
path = "../futures"

[dependencies.iced_style]
version = "0.3"
path = "../style"

[dependencies.web-sys]
version = "0.3.27"
features = [
    "console",
    "Document",
    "HtmlElement",
    "HtmlInputElement",
    "Event",
    "EventTarget",
    "InputEvent",
    "KeyboardEvent",
]
